# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
env:
  - _R_CHECK_FORCE_SUGGESTS_=false
sudo: false
cache: packages
warnings_are_errors: false # turn this back on for more severe testing

before_install:
  - Rscript -e 'utils::install.packages(c("blob", "DBI", "RSQLite"))'
  - git clone -b master --single-branch --recursive https://github.com/Burke-Lauenroth-Lab/rSOILWAT2.git /tmp/rSOILWAT2
  - R CMD INSTALL /tmp/rSOILWAT2

after_success:
  - Rscript -e 'covr::codecov()'
